services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'example'
    ports:
      - 5432:5432
    volumes:
      - .data:/var/lib/postgresql/data
